/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carrentalsystem;

import javax.swing.JFrame;

/**
 *
 * @author Nahom
 */
public class AdminMenu extends javax.swing.JFrame {

    /**
     * Creates new form AdminMenu
     */
    public AdminMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        listCombo = new javax.swing.JComboBox<>();
        searchField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        CarEditPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        newName = new javax.swing.JTextField();
        newId = new javax.swing.JTextField();
        carList2 = new javax.swing.JComboBox<>();
        rentButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        rentDate = new javax.swing.JTextField();
        returnDate = new javax.swing.JTextField();
        result = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        countResult = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        returnCar = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        customerIdCombo = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        plateDisplay = new javax.swing.JTextField();
        priceDisplay = new javax.swing.JTextField();
        dateDisplay = new javax.swing.JTextField();
        returnCarButton = new javax.swing.JButton();
        returnStatus = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        CarOperation = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        colorEdit = new javax.swing.JTextField();
        modelEdit = new javax.swing.JTextField();
        manufacturerEdit = new javax.swing.JTextField();
        priceEdit = new javax.swing.JTextField();
        speedEdit = new javax.swing.JTextField();
        quantityEdit = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        plateList = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        newPlate = new javax.swing.JTextField();
        newModel = new javax.swing.JTextField();
        newManufacturer = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        newPrice = new javax.swing.JTextField();
        newSpeed = new javax.swing.JTextField();
        newQuantity = new javax.swing.JTextField();
        newColor = new javax.swing.JComboBox<>();
        jLabel39 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        mainPanel.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Car Rental System Main Menu");
        mainPanel.add(jLabel1);
        jLabel1.setBounds(10, 11, 453, 40);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            DB.getRentedCars(),
            new String [] {
                "Customer Name", "Car Model", "Price", "speed","date Rented","date Returned","Current Quantity"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        mainPanel.add(jScrollPane1);
        jScrollPane1.setBounds(10, 110, 430, 210);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 204));
        jLabel2.setText("Recent Car Rents History");
        mainPanel.add(jLabel2);
        jLabel2.setBounds(10, 60, 270, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 204));
        jLabel3.setText("Total Cars Rented:");
        mainPanel.add(jLabel3);
        jLabel3.setBounds(470, 110, 110, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 204));
        jLabel4.setText("Total Income Earned: ");
        mainPanel.add(jLabel4);
        jLabel4.setBounds(470, 150, 120, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 204));
        jLabel5.setText("Count Cars By:");
        mainPanel.add(jLabel5);
        jLabel5.setBounds(470, 190, 90, 40);

        listCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "color", "speed", "Quantity","manufacturer" }));
        mainPanel.add(listCombo);
        listCombo.setBounds(560, 200, 100, 20);
        mainPanel.add(searchField);
        searchField.setBounds(670, 200, 70, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 204));
        jLabel6.setText("Select An Operation Below");
        mainPanel.add(jLabel6);
        jLabel6.setBounds(10, 340, 150, 40);

        jButton2.setText("Edit Car");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        mainPanel.add(jButton2);
        jButton2.setBounds(10, 430, 130, 30);

        jButton3.setText("Add New Car");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        mainPanel.add(jButton3);
        jButton3.setBounds(10, 470, 130, 30);

        CarEditPanel.setLayout(null);

        jLabel7.setText("Customer Name:");
        CarEditPanel.add(jLabel7);
        jLabel7.setBounds(10, 27, 85, 26);

        jLabel8.setText("Customer ID:");
        CarEditPanel.add(jLabel8);
        jLabel8.setBounds(10, 64, 85, 26);

        jLabel9.setText("Select Car:");
        CarEditPanel.add(jLabel9);
        jLabel9.setBounds(10, 101, 85, 29);
        CarEditPanel.add(newName);
        newName.setBounds(105, 30, 115, 20);
        CarEditPanel.add(newId);
        newId.setBounds(105, 64, 115, 26);

        carList2.setModel(new javax.swing.DefaultComboBoxModel<>(DB.getListBy("plateNumber")));
        CarEditPanel.add(carList2);
        carList2.setBounds(105, 101, 115, 24);

        rentButton.setText("Rent");
        rentButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rentButtonMouseClicked(evt);
            }
        });
        CarEditPanel.add(rentButton);
        rentButton.setBounds(256, 96, 99, 29);

        jLabel11.setText("Date Rented");
        CarEditPanel.add(jLabel11);
        jLabel11.setBounds(250, 30, 90, 20);

        jLabel37.setText("Date to Return: ");
        CarEditPanel.add(jLabel37);
        jLabel37.setBounds(250, 60, 90, 20);
        CarEditPanel.add(rentDate);
        rentDate.setBounds(350, 30, 100, 20);
        CarEditPanel.add(returnDate);
        returnDate.setBounds(350, 60, 100, 20);

        mainPanel.add(CarEditPanel);
        CarEditPanel.setBounds(220, 370, 510, 130);
        CarEditPanel.setVisible(false);

        result.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        result.setForeground(new java.awt.Color(255, 255, 51));
        mainPanel.add(result);
        result.setBounds(290, 330, 310, 30);

        jToggleButton1.setText("Rent Car");
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton1MouseClicked(evt);
            }
        });
        mainPanel.add(jToggleButton1);
        jToggleButton1.setBounds(10, 380, 130, 30);

        jButton1.setText("Count!");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        mainPanel.add(jButton1);
        jButton1.setBounds(560, 230, 100, 23);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 204));
        jLabel10.setText("Result:");
        mainPanel.add(jLabel10);
        jLabel10.setBounds(470, 270, 70, 30);

        countResult.setText("0");
        mainPanel.add(countResult);
        countResult.setBounds(540, 270, 40, 30);

        jLabel12.setText("Cars");
        mainPanel.add(jLabel12);
        jLabel12.setBounds(580, 274, 90, 20);

        jLabel13.setText("Customer ID:");

        jLabel14.setText("Car Plate:");

        customerIdCombo.setModel(new javax.swing.DefaultComboBoxModel<>(DB.getCustomerList("id")));
        customerIdCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                customerIdComboItemStateChanged(evt);
            }
        });

        jLabel15.setText("Car Price:");

        jLabel16.setText("Date:");

        returnCarButton.setText("Return");
        returnCarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnCarButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout returnCarLayout = new javax.swing.GroupLayout(returnCar);
        returnCar.setLayout(returnCarLayout);
        returnCarLayout.setHorizontalGroup(
            returnCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnCarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(returnCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(returnCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(returnCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(customerIdCombo, 0, 133, Short.MAX_VALUE)
                    .addComponent(plateDisplay)
                    .addComponent(priceDisplay)
                    .addComponent(dateDisplay))
                .addGap(18, 18, 18)
                .addGroup(returnCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(returnCarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .addComponent(returnStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        returnCarLayout.setVerticalGroup(
            returnCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnCarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(returnCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(returnCarLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(customerIdCombo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(returnCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plateDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(returnCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(returnCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnCarButton))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        mainPanel.add(returnCar);
        returnCar.setBounds(210, 360, 530, 150);
        returnCar.setVisible(false);

        jLabel33.setText("0");
        mainPanel.add(jLabel33);
        jLabel33.setBounds(590, 120, 50, 20);
        jLabel33.setText(String.valueOf(DB.getTotalCarsRented()));

        jLabel34.setText("0");
        mainPanel.add(jLabel34);
        jLabel34.setBounds(590, 150, 50, 20);
        jLabel34.setText(String.valueOf(DB.getTotalIncomeEarned()));

        jLabel35.setText("cars");
        mainPanel.add(jLabel35);
        jLabel35.setBounds(650, 120, 50, 20);

        jLabel36.setText("ETB");
        mainPanel.add(jLabel36);
        jLabel36.setBounds(650, 160, 50, 20);

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/showroom.jpg"))); // NOI18N
        mainPanel.add(jLabel38);
        jLabel38.setBounds(0, 0, 760, 520);

        getContentPane().add(mainPanel);
        mainPanel.setBounds(0, 0, 760, 530);
        mainPanel.setVisible(true);

        CarOperation.setLayout(null);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 204, 153));
        jLabel17.setText("Car Garage");
        CarOperation.add(jLabel17);
        jLabel17.setBounds(10, 11, 328, 66);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 102));
        jLabel18.setText("Cars You have Added So far");
        CarOperation.add(jLabel18);
        jLabel18.setBounds(10, 80, 270, 40);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            DB.getCarTable(),
            new String [] {
                "Plate", "Model", "Manufacturer", "color","price","speed","quantity"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        CarOperation.add(jScrollPane2);
        jScrollPane2.setBounds(10, 120, 440, 210);

        jLabel19.setText("Plate Number:");
        CarOperation.add(jLabel19);
        jLabel19.setBounds(450, 120, 90, 40);

        jLabel20.setText("Color:");
        CarOperation.add(jLabel20);
        jLabel20.setBounds(450, 170, 60, 30);

        jLabel21.setText("Model:");
        CarOperation.add(jLabel21);
        jLabel21.setBounds(450, 220, 70, 20);

        jLabel22.setText("Manufacturer:");
        CarOperation.add(jLabel22);
        jLabel22.setBounds(450, 270, 90, 30);

        jLabel23.setText("Price:");
        CarOperation.add(jLabel23);
        jLabel23.setBounds(450, 320, 70, 20);

        jLabel24.setText("Speed:");
        CarOperation.add(jLabel24);
        jLabel24.setBounds(450, 360, 60, 20);

        jLabel25.setText("Quantity:");
        CarOperation.add(jLabel25);
        jLabel25.setBounds(450, 400, 50, 30);
        CarOperation.add(colorEdit);
        colorEdit.setBounds(530, 170, 90, 20);
        CarOperation.add(modelEdit);
        modelEdit.setBounds(530, 220, 90, 20);
        CarOperation.add(manufacturerEdit);
        manufacturerEdit.setBounds(530, 270, 90, 20);
        CarOperation.add(priceEdit);
        priceEdit.setBounds(530, 320, 90, 20);
        CarOperation.add(speedEdit);
        speedEdit.setBounds(530, 360, 90, 20);
        CarOperation.add(quantityEdit);
        quantityEdit.setBounds(530, 400, 90, 20);

        update.setText("Update");
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
        });
        CarOperation.add(update);
        update.setBounds(450, 450, 100, 30);

        delete.setText("Delete!");
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });
        CarOperation.add(delete);
        delete.setBounds(560, 450, 100, 30);

        plateList.setModel(new javax.swing.DefaultComboBoxModel<>(DB.getListBy("plateNumber")));
        plateList.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                plateListItemStateChanged(evt);
            }
        });
        CarOperation.add(plateList);
        plateList.setBounds(530, 130, 90, 20);

        jLabel26.setText("plate Number: ");
        CarOperation.add(jLabel26);
        jLabel26.setBounds(10, 350, 90, 30);

        jLabel27.setText("Color:");
        CarOperation.add(jLabel27);
        jLabel27.setBounds(10, 390, 80, 20);

        jLabel28.setText("Model:");
        CarOperation.add(jLabel28);
        jLabel28.setBounds(10, 430, 70, 20);

        jLabel29.setText("Manufacture:");
        CarOperation.add(jLabel29);
        jLabel29.setBounds(10, 470, 70, 30);
        CarOperation.add(newPlate);
        newPlate.setBounds(100, 360, 90, 20);
        CarOperation.add(newModel);
        newModel.setBounds(100, 430, 90, 20);
        CarOperation.add(newManufacturer);
        newManufacturer.setBounds(100, 470, 90, 20);

        jLabel30.setText("Price:");
        CarOperation.add(jLabel30);
        jLabel30.setBounds(200, 360, 70, 20);

        jLabel31.setText("Speed:");
        CarOperation.add(jLabel31);
        jLabel31.setBounds(200, 390, 60, 20);

        jLabel32.setText("Quantity:");
        CarOperation.add(jLabel32);
        jLabel32.setBounds(200, 430, 60, 20);

        submit.setText("Submit");
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitMouseClicked(evt);
            }
        });
        CarOperation.add(submit);
        submit.setBounds(240, 460, 120, 30);
        CarOperation.add(newPrice);
        newPrice.setBounds(240, 360, 90, 20);
        CarOperation.add(newSpeed);
        newSpeed.setBounds(240, 390, 90, 20);
        CarOperation.add(newQuantity);
        newQuantity.setBounds(250, 430, 80, 20);

        newColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Black", "White", "Red", "Green","Blue","cyan","Grey","Yellow","Brown","Metal","Orange","Pink" }));
        CarOperation.add(newColor);
        newColor.setBounds(100, 390, 90, 20);

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/store.jpg"))); // NOI18N
        CarOperation.add(jLabel39);
        jLabel39.setBounds(0, 0, 760, 520);

        getContentPane().add(CarOperation);
        CarOperation.setBounds(0, 0, 760, 520);
        CarOperation.setVisible(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseClicked
        if(jToggleButton1.isSelected()){
            returnCar.setVisible(false);
            CarEditPanel.setVisible(true);
            jToggleButton1.setText("Return Car");
        }
        else{
            returnCar.setVisible(true);
            CarEditPanel.setVisible(false);
            jToggleButton1.setText("Rent Car");
        }
    }//GEN-LAST:event_jToggleButton1MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String plate=(String)this.listCombo.getSelectedItem();
        String item=this.searchField.getText();
        int count=DB.getTotalNumberOfCars(plate, item);
        countResult.setText(String.valueOf(count));
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void rentButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rentButtonMouseClicked
        String name=this.newName.getText();
        String id=this.newId.getText();
        String plate=(String)this.carList2.getSelectedItem();
        String date1=this.rentDate.getText();
        String date2=this.returnDate.getText();
        int quantity=Integer.parseInt(DB.getValue("quantity",plate));
        quantity=quantity-1;
        String q=String.valueOf(quantity);
        String subQuery="update car set quantity='"+q+"' where plateNumber='"+plate+"'";
        String query="insert into rent values('"+plate+"','"+id+"','"+date1+"','"+date2+"')";
        String query2="insert into customer values('"+id+"','"+name+"')";
        DB.execute(query2);
        DB.execute(query);
        DB.execute(subQuery);
        this.dispose();
        AdminMenu menu=new AdminMenu();
        menu.setTitle("Administrator Men");
        menu.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        menu.setVisible(true);
        menu.result.setText("Rented 1 Car");
    }//GEN-LAST:event_rentButtonMouseClicked

    private void customerIdComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_customerIdComboItemStateChanged
        String id=(String)customerIdCombo.getSelectedItem();
        this.plateDisplay.setText(DB.getSelectedColumn("plateNumber", id));
        this.priceDisplay.setText(DB.getSelectedColumn("price", id));
        this.dateDisplay.setText(DB.getSelectedColumn("rentDate", id));
        
    }//GEN-LAST:event_customerIdComboItemStateChanged

    private void returnCarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnCarButtonMouseClicked
        String id=(String)customerIdCombo.getSelectedItem();
        String query="delete from rent where customerid='"+id+"'";
        int quantity=Integer.parseInt(DB.getValue("quantity",DB.getSelectedColumn("plateNumber", id)));
        quantity=quantity+1;
        String q=String.valueOf(quantity);
        String subQuery="update car set quantity='"+q+"' where plateNumber='"+plateDisplay.getText()+"'";
        DB.execute(subQuery);
        DB.execute(query);
        this.dispose();
        AdminMenu menu=new AdminMenu();
        menu.setTitle("Administrator Menu");
        menu.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        menu.setVisible(true);
        menu.result.setText("Returned 1 Car");
    }//GEN-LAST:event_returnCarButtonMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        mainPanel.setVisible(false);
        CarOperation.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        mainPanel.setVisible(false);
        CarOperation.setVisible(true);
    }//GEN-LAST:event_jButton3MouseClicked

    private void plateListItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_plateListItemStateChanged
        String plateNumber=(String)plateList.getSelectedItem();
        this.colorEdit.setText(DB.getSelectedColumn("color", plateNumber));
        this.priceEdit.setText(DB.getSelectedColumn("price", plateNumber));
        this.speedEdit.setText(DB.getSelectedColumn("speed", plateNumber));
        this.modelEdit.setText(DB.getSelectedColumn("model", plateNumber));
        this.manufacturerEdit.setText(DB.getSelectedColumn("manfucturer", plateNumber));
        this.quantityEdit.setText(DB.getSelectedColumn("quantity", plateNumber));
    }//GEN-LAST:event_plateListItemStateChanged

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
        String plateNumber=(String)plateList.getSelectedItem();
        String model=modelEdit.getText();
        String manufacturer=manufacturerEdit.getText();
        String color=colorEdit.getText();
        int price=Integer.parseInt(priceEdit.getText());
        String speed=speedEdit.getText();
        String quantity=quantityEdit.getText();
        String query="update car set model='"+model+"', manfucturer='"+manufacturer+"', color='"+color+"', price='"+price+"',speed='"+speed+"', quantity='"+quantity+"' where platenumber='"+plateNumber+"'";
        DB.execute(query);
        this.dispose();
        AdminMenu menu=new AdminMenu();
        menu.setTitle("Administrator Menu");
        menu.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        menu.setVisible(true);
        menu.CarOperation.setVisible(true);
        menu.mainPanel.setVisible(false);
        menu.result.setText("1 Car Updated!");
        
        
        
    }//GEN-LAST:event_updateMouseClicked

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        String plateNumber=(String)plateList.getSelectedItem();
        String query="delete from car where plateNumber='"+plateNumber+"'";
        DB.execute(query);
        this.dispose();
        AdminMenu menu=new AdminMenu();
        menu.setTitle("Administrator Menu");
        menu.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        menu.setVisible(true);
        menu.CarOperation.setVisible(true);
        menu.mainPanel.setVisible(false);
        menu.result.setText("1 Car Deleted!");
        
    }//GEN-LAST:event_deleteMouseClicked

    private void submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseClicked
        String pno=this.newPlate.getText();
        String model=newModel.getText();
        String mnf=newManufacturer.getText();
        String color=(String)newColor.getSelectedItem();
        String price=newPrice.getText();
        String speed=newSpeed.getText();
        String quantity=newQuantity.getText();
        String query="insert into car values ('"+pno+"','"+model+"','"+mnf+"','"+color+"','"+price+"','"+speed+"','"+quantity+"')";
        DB.execute(query);
        this.dispose();
        AdminMenu menu=new AdminMenu();
        menu.setTitle("Administrator Menu");
        menu.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        menu.setVisible(true);
        menu.CarOperation.setVisible(true);
        menu.mainPanel.setVisible(false);
        menu.result.setText("1 Car Added!");
       
    }//GEN-LAST:event_submitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CarEditPanel;
    private javax.swing.JPanel CarOperation;
    private javax.swing.JComboBox<String> carList2;
    private javax.swing.JTextField colorEdit;
    private javax.swing.JLabel countResult;
    private javax.swing.JComboBox<String> customerIdCombo;
    private javax.swing.JTextField dateDisplay;
    private javax.swing.JButton delete;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JComboBox<String> listCombo;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField manufacturerEdit;
    private javax.swing.JTextField modelEdit;
    private javax.swing.JComboBox<String> newColor;
    private javax.swing.JTextField newId;
    private javax.swing.JTextField newManufacturer;
    private javax.swing.JTextField newModel;
    private javax.swing.JTextField newName;
    private javax.swing.JTextField newPlate;
    private javax.swing.JTextField newPrice;
    private javax.swing.JTextField newQuantity;
    private javax.swing.JTextField newSpeed;
    private javax.swing.JTextField plateDisplay;
    private javax.swing.JComboBox<String> plateList;
    private javax.swing.JTextField priceDisplay;
    private javax.swing.JTextField priceEdit;
    private javax.swing.JTextField quantityEdit;
    private javax.swing.JButton rentButton;
    private javax.swing.JTextField rentDate;
    private javax.swing.JLabel result;
    private javax.swing.JPanel returnCar;
    private javax.swing.JButton returnCarButton;
    private javax.swing.JTextField returnDate;
    private javax.swing.JLabel returnStatus;
    private javax.swing.JTextField searchField;
    private javax.swing.JTextField speedEdit;
    private javax.swing.JButton submit;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
